network: Exit with Return Code when VM start Fails
Added failure detection to the --vm-start functionality
so that the ha agent can receive failures via the failed
exit code in order to increase the retry count and penalize
the host. Thus lowering the host's score for rescheduling.

Change-Id: Id02a9ec5b48321df79067e72de5434d69706cb29
Bug-Url: https://bugzilla.redhat.com/1627958
Signed-off-by: Steven Rosenberg <srosenbe@redhat.com>

diff --git a/src/bin/hosted-engine.in b/src/bin/hosted-engine.in
--- a/src/bin/hosted-engine.in
+++ b/src/bin/hosted-engine.in
@@ -184,7 +184,12 @@ return ;}
         else
             vmconf="${conf}"
         fi
-        ${VDSMHELPER} create "${vmconf}"
+        if ${VDSMHELPER} create "${vmconf}"; then
+            echo "VM in WaitForLaunch"
+        else
+            echo "VM failed to launch"
+            exit 1
+        fi
     else
         exit_not_deployed
     fi
