bin: die not defined
fixed hosted-engine script that called die
instead of usage on invalid argument.

Change-Id: Ia68ea1c1b61472e0e50302a1adc46b0202019214
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

diff --git a/src/bin/hosted-engine.in b/src/bin/hosted-engine.in
--- a/src/bin/hosted-engine.in
+++ b/src/bin/hosted-engine.in
@@ -70,7 +70,8 @@ while [ -n "$1" ]; do
             usage
         ;;
         *)
-            die "Invalid option '${x}'"
+            echo "Invalid option '${x}'" >&2
+            usage
         ;;
     esac
 done
