Avoid failing --start-paused if the VM is in down state
Change-Id: I30dc86b5c551ace2d78859b14431f06543f23fee
Bug-Url: https://bugzilla.redhat.com/1715080
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
(cherry picked from commit f8402adbd8ff034466dab5bee3a415437bc4af9e)

diff --git a/src/bin/hosted-engine.in b/src/bin/hosted-engine.in
--- a/src/bin/hosted-engine.in
+++ b/src/bin/hosted-engine.in
@@ -206,11 +206,27 @@ return ;}
     # TODO: Check first the sanlock status, and if allows:
     if [ -n "${vmid}" ] ; then
         check_vm_conf
+        local down=
+        local status=
+        status=$(${VDSMHELPER} checkVmStatus ${vmid})
+        if [[ $status == *"Down"* ]]; then
+            echo "VM exists and is down, cleaning up and restarting"
+            ${VDSMHELPER} destroy "${vmid}"
+        elif [ -n "${status}" ]; then
+            echo "VM exists and its status is ${status}"
+            exit 1
+        fi
         temp_conf="$(mktemp)"
         cp "${conf}" "${temp_conf}"
         echo "launchPaused=true">>"${temp_conf}"
-        ${VDSMHELPER} create "${temp_conf}"
-        rm -f "${temp_conf}"
+        if ${VDSMHELPER} create "${temp_conf}"; then
+            rm -f "${temp_conf}"
+            echo "VM in WaitForLaunch"
+        else
+            rm -f "${temp_conf}"
+            echo "VM failed to launch"
+            exit 1
+        fi
     else
         exit_not_deployed
     fi
